# sample comes from https://github.com/docker/awesome-compose

services:
  frontend:
    image: alswl/excalidraw:v0.17.3-fork-b1
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=http://storage:8081/api/v2/scenes/
      - VITE_APP_BACKEND_V2_POST_URL=http://storage:8081/api/v2/scenes/
      - VITE_APP_WS_SERVER_URL=http://room:8082
      - VITE_APP_FIREBASE_CONFIG={}
      # alswl'fork env
      # forked excalidraw can use env https://github.com/alswl/excalidraw/pull/5
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=http://storage:8081/api/v2
      - VITE_APP_STORAGE_BACKEND=http
    healthcheck:
      test: "curl -sf http://localhost"
      
  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: unless-stopped
    environment:
      - STORAGE_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    restart: unless-stopped


  mongodb:
    image: mongo:7.0.5-jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - excalidraw-mongodb:/data/db
    user: "1000"
    
volumes:
  excalidraw-mongodb:
